openapi: 3.0.0
info:
  title: Credit API
  version: 1.0.0
servers:
  - url: https://api.staging.greentesting.ir
  - url: http://localhost:8080
paths:
  /v1/credit-refund/store:
    post:
      tags:
        - Credit Refunds
      summary: Store
      operationId: 1a7796f9a5c48e2284725023bf37b39a
      requestBody:
        description: Data to refund credit
        required: true
        content:
          application/json:
            schema:
              properties:
                iban:
                  description: IBAN
                  type: string
                client_name:
                  description: Client Name
                  type: string
              type: object
      responses:
        '200':
          description: Credit refunded successfully
          content:
            application/json:
              schema:
                properties:
                  success:
                    type: boolean
                  data:
                    properties:
                      ticket_id:
                        type: string
                      ticket_cid:
                        type: string
                    type: object
                type: object
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      details:
                        type: object
                      msgType:
                        type: string
                    type: object
                type: object
        '401':
          description: Unauthorized Request
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                        example: پارامتر ها ناقص است
                      details:
                        properties:
                          iban:
                            type: array
                            items:
                              type: string
                              example: Iban الزامی است
                        type: object
                      msgType:
                        type: string
                        example: App\\Exceptions\\BasicException\\ValidationApiException
                    type: object
                type: object
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                properties:
                  error:
                    properties:
                      message:
                        type: string
                      details:
                        type: object
                      msgType:
                        type: string
                    type: object
                type: object
      security:
        - bearerAuth: []
  /v1/invoices:
    get:
      tags:
        - Invoices
      summary: Index
      description: Retrieves a list of invoices based on various parameters.
      operationId: 966c79ab1e77eff6618e40da4938246e
      parameters:
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
            nullable: true
        - name: per_page
          in: query
          description: Items per page
          schema:
            type: integer
            nullable: true
        - name: sort[field]
          in: query
          description: Field to sort by
          schema:
            type: string
            nullable: true
        - name: sort[order]
          in: query
          description: Sort order (ASC/DESC)
          schema:
            type: string
            nullable: true
        - name: status
          in: query
          description: Invoice status
          schema:
            type: array
            nullable: true
        - name: search[id]
          in: query
          description: Search by ID
          schema:
            type: string
            nullable: true
        - name: search
          in: query
          description: Search parameter
          schema:
            type: string
            nullable: true
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '401':
          description: Unauthorized Request
        '404':
          description: Not found
        '422':
          description: Valiation Error
      security:
        - bearerAuth: []
components:
  parameters:
    Is-Api-Token:
      name: Is-Api-Token
      in: header
      description: Your API Token Description
      required: true
      schema:
        type: string
        default: 0R6Ba53tsPGp6gou
  securitySchemes:
    bearerAuth:
      type: http
      bearerFormat: JWT
      scheme: bearer
